### ISSUE TITLE
Radar Map

### ISSUE THREAD

**Issue by Kawilder** [SepidehAyani/WeatheredVibes#14]
Fetch api for 
     google maps, 
     weather radar, 
     geocoding

Optimize number of api calls

Improve user experience/interface by showing county/state names on map

Add buttons to change weather radar overlay
     (I.e. precipitation, wind speed, temperature, clouds)

**Comment by SepidehAyani** [comment]
remained open for future enhancement.

**Comment by SepidehAyani** [comment]
radar map api has been added.
